# Generated by Django 5.1.5 on 2026-05-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_recruiter_contact_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlassdoorCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("company_link", models.URLField(blank=True, max_length=1000)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("review_count", models.IntegerField(default=0)),
                ("salary_count", models.IntegerField(default=0)),
                ("job_count", models.IntegerField(default=0)),
                ("headquarters_location", models.CharField(blank=True, max_length=255)),
                ("logo", models.URLField(blank=True, max_length=1000)),
                ("company_size", models.CharField(blank=True, max_length=255)),
                ("company_description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=255)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("revenue", models.CharField(blank=True, max_length=255)),
                ("ceo", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Glassdoor companies",
                "ordering": ["name"],
            },
        ),
        migrations.RenameIndex(
            model_name="scrapedjob",
            new_name="tasks_scrap_search__96ee05_idx",
            old_name="tasks_scrap_search__3102b1_idx",
        ),
    ]
