# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_glassdoorcompany_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="glassdoorcompany",
            name="best_places_to_work_awards",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="business_outlook_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="career_opportunities_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="ceo_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="company_size_category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="company_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="compensation_and_benefits_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="competitors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="culture_and_values_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="diversity_and_inclusion_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="faq_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="jobs_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="office_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="raw",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="recommend_to_friend_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="reviews_link",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="senior_management_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="stock",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="work_life_balance_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="glassdoorcompany",
            name="year_founded",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
