# Generated by Django 5.2.14 on 2026-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_extend_glassdoorcompany"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=40)),
                ("source_id", models.CharField(max_length=120)),
                (
                    "search_query",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("position", models.CharField(blank=True, max_length=500)),
                ("seniority", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("company_domain", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("linkedin_url", models.URLField(blank=True, max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["search_query", "source"],
                        name="tasks_cache_search__344e6e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="unique_cached_person_per_source",
                    )
                ],
            },
        ),
    ]
